name: Build Kodi Repository

on:
  push:
    branches: [ master ]
    paths:
      - 'repo/**'        # Só roda se algo mudar dentro da pasta repo/

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar o repositório
      uses: actions/checkout@v3

    - name: Instalar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Executar script de build (gerar addons.xml, MD5 e ZIPs)
      run: python _repo_generator.py

    - name: Commit e push dos arquivos gerados
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@users.noreply.github.com"
        git add .
        git commit -m "Atualização automática: arquivos gerados por build.py" || echo "Nada para commitar"
        git push
