name: Build Kodi Repository

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar o repositório
      uses: actions/checkout@v3

    - name: Instalar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Executar script de build (gerar addons.xml, MD5 e ZIPs)
      run: python _repo_generator.py
