name: Publicar site

on:
  push:
    branches: [ master ]

jobs:
  deploy-site:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
    - name: Checkout do repositório
      uses: actions/checkout@v3

    - name: Configurar GitHub Pages
      uses: actions/configure-pages@v4

    - name: Enviar arquivos do site (index.html)
      uses: actions/upload-pages-artifact@v4
      with:
        path: .  # envia tudo da raiz — incluindo index.html

    - name: Publicar no GitHub Pages
      uses: actions/deploy-pages@v3
